version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  website:
    depends_on:
      - 'db'
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/work-time'
    volumes_from:
    - box

  box:
    image: busybox
    volumes:
      - /box

volumes:
    db_data: {}
    box: